insert into public.content_entries (kind, slug, title, status, featured, data)
values
  ('settings', 'site-settings', 'James Fontanilla', 'published', true, '{"name":"James Fontanilla","role":"Full-Stack Developer","tagline":"Premium, app-like portfolio for projects, proof, and contact.","summary":"A desktop-optimized portfolio inspired by sleek mobile dashboards, rebuilt as a clear workspace for your work, certifications, events, and private publishing.","intro":"Available for freelance and collaboration","bio":"Design-led, product-minded, and curious about systems.","location":"Philippines / Remote","availability":"Available for freelance and collaboration","email":"jamesfontanilla@outlook.ph","phoneNumber":"+639282180937","githubUrl":"https://github.com/jamesfontanilla","linkedinUrl":"https://www.linkedin.com/in/jamesrfontanilla/","xUrl":"https://x.com/thinkaboutjaime","threadsUrl":"https://www.threads.com/@jxmsfnt","resumeUrl":"#","facebookUrl":"https://www.facebook.com/jamesrfontanilla/","instagramUrl":"https://www.instagram.com/jxmsnft/"}'::jsonb),
  ('project', 'portfolio-command-center', 'Portfolio command center', 'published', true, '{"summary":"A polished portfolio shell with a dashboard feel, admin publishing, and a clean content structure for projects and proof.","status":"Live","stack":["Next.js","TypeScript"],"impact":"Impact: premium first impression","demoUrl":"#","repoUrl":"#","featured":true}'::jsonb),
  ('project', 'commerce-dashboard-revamp', 'Commerce dashboard revamp', 'published', false, '{"summary":"A conversion-focused redesign with clearer hierarchy, faster scanning, and a more premium visual language.","status":"Case Study","stack":["UI / UX","Product"],"impact":"Impact: stronger conversion clarity","featured":false}'::jsonb),
  ('project', 'reusable-component-kit', 'Reusable component kit', 'published', false, '{"summary":"A personal design system built to speed up future products while keeping the interface cohesive.","status":"Open Source","stack":["React","Design System"],"impact":"Impact: faster future builds","featured":false}'::jsonb),
  ('certification', 'frontend-fundamentals', 'Frontend Fundamentals', 'published', false, '{"issuer":"Issuer Name","earnedOn":"2026-04-01","verificationUrl":"#"}'::jsonb),
  ('certification', 'ui-design-systems', 'UI Design Systems', 'published', false, '{"issuer":"Issuer Name","earnedOn":"2026-06-01","verificationUrl":"#"}'::jsonb),
  ('certification', 'cloud-basics', 'Cloud Basics', 'published', false, '{"issuer":"Issuer Name","earnedOn":"2026-07-01","verificationUrl":"#"}'::jsonb),
  ('event', 'developer-summit-manila', 'Developer Summit Manila', 'published', true, '{"type":"Conference","role":"Attendee","date":"2026-05-12","location":"Manila","summary":"Showcase event photos, a recap, and what you learned. This card can be expanded into a post detail page later.","tags":["Media","Conference"]}'::jsonb),
  ('event', 'hackathon-weekend', 'Hackathon weekend', 'published', false, '{"type":"Hackathon","role":"Participant","date":"2026-03-18","summary":"Team shot, prototype screenshots, and a short summary.","tags":["Prototype","Team"]}'::jsonb),
  ('event', 'community-meetup', 'Community meetup', 'published', false, '{"type":"Meetup","role":"Speaker","date":"2026-02-08","summary":"Speaker photo, notes, and the topics you discussed.","tags":["Talk","Community"]}'::jsonb),
  ('event', 'workshop-bootcamp', 'Workshop / bootcamp', 'published', false, '{"type":"Workshop","role":"Learner","date":"2026-01-20","summary":"Certificates, event badge, and a media gallery.","tags":["Learning","Media"]}'::jsonb),
  ('blog', 'building-os-portfolio', 'Building an OS-style portfolio with Next.js', 'published', true, '{"slug":"building-os-portfolio","excerpt":"How I built a browser-based desktop OS experience using React, CSS glassmorphism, and the Web Animations API.","tags":["Next.js","React","CSS"],"publishedAt":"2026-07-10","featured":true}'::jsonb)
on conflict (kind, slug) do update set
  title = excluded.title,
  status = excluded.status,
  featured = excluded.featured,
  data = excluded.data;
