import type { HomeData } from "@/lib/types";

export const fallbackHomeData: HomeData = {
  settings: {
    name: "James Fontanilla",
    role: "Full-Stack Developer",
    tagline: "Premium, app-like portfolio for projects, proof, and contact.",
    summary:
      "A desktop-optimized portfolio inspired by sleek mobile dashboards, rebuilt as a clear workspace for your work, certifications, events, and private publishing.",
    intro: "Available for freelance and collaboration",
    bio: "Design-led, product-minded, and curious about systems.",
    location: "Philippines / Remote",
    availability: "Available for freelance and collaboration",
    email: "jamesfontanilla@outlook.ph",
    phoneNumber: "+639282180937",
    githubUrl: "https://github.com/jamesfontanilla",
    linkedinUrl: "https://www.linkedin.com/in/jamesrfontanilla/",
    xUrl: "https://x.com/thinkaboutjaime",
    threadsUrl: "https://www.threads.com/@jxmsfnt",
    resumeUrl: "#",
    facebookUrl: "https://www.facebook.com/jamesrfontanilla/",
    instagramUrl: "https://www.instagram.com/jxmsnft/",
  },
  projects: [
    {
      title: "Portfolio command center",
      summary:
        "A polished portfolio shell with a dashboard feel, admin publishing, and a clean content structure for projects and proof.",
      status: "Live",
      stack: ["Next.js", "TypeScript"],
      impact: "Impact: premium first impression",
      demoUrl: "#",
      repoUrl: "#",
      featured: true,
    },
    {
      title: "Commerce dashboard revamp",
      summary:
        "A conversion-focused redesign with clearer hierarchy, faster scanning, and a more premium visual language.",
      status: "Case Study",
      stack: ["UI / UX", "Product"],
      impact: "Impact: stronger conversion clarity",
    },
    {
      title: "Reusable component kit",
      summary:
        "A personal design system built to speed up future products while keeping the interface cohesive.",
      status: "Open Source",
      stack: ["React", "Design System"],
      impact: "Impact: faster future builds",
    },
  ],
  certifications: [
    {
      title: "Frontend Fundamentals",
      issuer: "Issuer Name",
      earnedOn: "2026-04-01",
      verificationUrl: "#",
    },
    {
      title: "UI Design Systems",
      issuer: "Issuer Name",
      earnedOn: "2026-06-01",
      verificationUrl: "#",
    },
    {
      title: "Cloud Basics",
      issuer: "Issuer Name",
      earnedOn: "2026-07-01",
      verificationUrl: "#",
    },
  ],
  events: [
    {
      title: "Hello, World! Your First Steps into AI and Microsoft",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-31",
      location: "Philippines / Online",
      summary: "An introductory session on getting started with AI and Microsoft technologies, designed to help learners take their first practical steps.",
      tags: ["AI", "Microsoft", "Learning"],
    },
    {
      title: "AppBuildersPH Meetup: Shipaton Edition",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-30",
      location: "Philippines / Online",
      summary: "A builder-focused meetup about turning ideas into shipped products through rapid prototyping, collaboration, and practical delivery lessons.",
      tags: ["App Building", "Community", "Product"],
    },
    {
      title: "AWSPEAK Victory: Fail Forward Fluently",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-30",
      location: "Philippines / Online",
      summary: "A community session on learning from setbacks, iterating with confidence, and building stronger cloud projects through continuous improvement.",
      tags: ["AWS", "Cloud", "Community"],
    },
    {
      title: "Seekers Guild Open Table: Compass and Conversation VI",
      type: "Community Event",
      role: "Learner",
      date: "2026-07-26",
      location: "Philippines / Online",
      summary: "An open conversation space for exchanging perspectives, finding direction, and connecting with other curious members of the community.",
      tags: ["Community", "Conversation", "Networking"],
    },
    {
      title: "WordPress Manila Meetup - July 2026",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-25",
      location: "Manila",
      summary: "A WordPress community gathering covering practical web building, publishing, and the ideas shaping the local WordPress ecosystem.",
      tags: ["WordPress", "Web Development", "Community"],
    },
    {
      title: "Build Nights: Data Pipelines & Analytics Dashboard with Kiro",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-24",
      location: "Philippines / Online",
      summary: "A hands-on build night for connecting data pipelines to an analytics dashboard with Kiro and turning raw data into useful product insights.",
      tags: ["Kiro", "Data Engineering", "Analytics"],
    },
    {
      title: "AWSUG PH July Meetup: Amazon Connect",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-23",
      location: "Philippines / Online",
      summary: "A user-group session exploring Amazon Connect and the cloud building blocks behind modern customer service experiences.",
      tags: ["AWS", "Amazon Connect", "Cloud"],
    },
    {
      title: "AWS BuilderCards Game Night",
      type: "Game Night",
      role: "Participant",
      date: "2026-07-20",
      location: "Philippines / Online",
      summary: "A playful AWS learning session using BuilderCards to reinforce cloud concepts through collaboration, problem-solving, and friendly competition.",
      tags: ["AWS", "Learning", "Community"],
    },
    {
      title: "AI Pilipinas Meetup #33: Claude Code Masterclass",
      type: "Masterclass",
      role: "Attendee",
      date: "2026-07-18",
      location: "Philippines / Online",
      summary: "A practical masterclass on using Claude Code to work more effectively with AI-assisted software development and developer workflows.",
      tags: ["AI", "Claude Code", "Developer Tools"],
    },
    {
      title: "Build Nights: Full-Stack Web App with Kiro",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-17",
      location: "Philippines / Online",
      summary: "A guided build session focused on creating a full-stack web application with Kiro, from interface to working application flow.",
      tags: ["Kiro", "Full Stack", "Web Development"],
    },
    {
      title: "[AWS SBG PUP] Building an End-to-End Serverless Data Pipeline with AWS",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-13",
      location: "PUP, Manila",
      summary: "A practical AWS session on designing an end-to-end serverless data pipeline, connecting ingestion, processing, storage, and analytics.",
      tags: ["AWS", "Serverless", "Data Engineering"],
    },
    {
      title: "Claude Code Manila Meetup #2",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-11",
      location: "Manila",
      summary: "A local developer meetup for sharing Claude Code workflows, experiments, and practical lessons from building with AI.",
      tags: ["AI", "Claude Code", "Developer Community"],
    },
    {
      title: "[FuseSpark] AI Workflow: The New Speed of Building",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-11",
      location: "Philippines / Online",
      summary: "A session on how AI-assisted workflows are changing the pace of product development, from idea exploration to implementation.",
      tags: ["AI", "Workflow", "Productivity"],
    },
    {
      title: "Build Nights: Kiro Web Autonomous Agent Workshop",
      type: "Workshop",
      role: "Attendee",
      date: "2026-07-10",
      location: "Philippines / Online",
      summary: "A hands-on workshop exploring autonomous web agents with Kiro and the patterns behind AI-assisted web experiences.",
      tags: ["Kiro", "AI Agents", "Web Development"],
    },
    {
      title: "Microsoft Azure Community Night - July Meetup",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-10",
      location: "Philippines / Online",
      summary: "A Microsoft Azure community gathering for learning, sharing cloud practices, and connecting with fellow developers and cloud practitioners.",
      tags: ["Microsoft Azure", "Cloud", "Community"],
    },
    {
      title: "Java User Group Philippines Meetup - July 2026",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-09",
      location: "Philippines / Online",
      summary: "A Java community meetup for exchanging development practices, platform updates, and experiences from the Philippine Java ecosystem.",
      tags: ["Java", "Software Development", "Community"],
    },
    {
      title: "PH Cloud Educators Community Meetup #1",
      type: "Meetup",
      role: "Attendee",
      date: "2026-07-04",
      location: "Philippines / Online",
      summary: "The first community meetup for cloud educators in the Philippines, focused on sharing teaching practices, cloud knowledge, and learning resources.",
      tags: ["Cloud", "Education", "Community"],
    },
    {
      title: "Huawei Cloud Developer Group – Kickoff Event",
      type: "Community Event",
      role: "Attendee",
      date: "2026-06-30",
      location: "Philippines / Online",
      summary: "A kickoff gathering for developers interested in Huawei Cloud, introducing the community and creating space for future technical collaboration.",
      tags: ["Huawei Cloud", "Cloud", "Developer Community"],
    },
    {
      title: "Tempest: Ascend to the Cloud",
      type: "Conference",
      role: "Attendee",
      date: "2026-06-30",
      location: "Philippines / Online",
      summary: "A cloud-focused event about modern infrastructure, platform growth, and the skills needed to move confidently into cloud development.",
      tags: ["Cloud", "Infrastructure", "Learning"],
    },
    {
      title: "AWS Skill Builder Execution Workshop",
      type: "Workshop",
      role: "Learner",
      date: "2026-06-29",
      location: "Philippines / Online",
      summary: "A focused learning workshop for applying AWS Skill Builder lessons through structured practice and hands-on cloud execution.",
      tags: ["AWS", "Cloud Learning", "Hands-On"],
    },
    {
      title: "Celestial Effervescence: Serverless APIs with Lambda + API Gateway",
      type: "Workshop",
      role: "Attendee",
      date: "2026-06-28",
      location: "Philippines / Online",
      summary: "A serverless development session on building and exposing APIs with AWS Lambda and API Gateway.",
      tags: ["AWS", "Serverless", "APIs"],
    },
    {
      title: "Launching Private Alf: Build & Deploy on EC2 with VPC",
      type: "Workshop",
      role: "Attendee",
      date: "2026-06-27",
      location: "Philippines / Online",
      summary: "A practical deployment session covering how to build and run an application on EC2 within a VPC-based AWS network.",
      tags: ["AWS", "EC2", "VPC"],
    },
    {
      title: "Microsoft Build //localhost: Manila",
      type: "Community Event",
      role: "Attendee",
      date: "2026-06-26",
      location: "Manila",
      summary: "A local Microsoft Build gathering bringing developers together to explore announcements, tools, and practical opportunities across the Microsoft platform.",
      tags: ["Microsoft", "Developer Community", "AI"],
    },
    {
      title: "Light up Your AI With Workato Enterprise MCP",
      type: "Workshop",
      role: "Attendee",
      date: "2026-06-23",
      location: "Philippines / Online",
      summary: "A session on connecting AI workflows with enterprise systems through Workato and the Model Context Protocol.",
      tags: ["AI", "MCP", "Automation"],
    },
    {
      title: "Data Engineering Pilipinas Year 3 Meetup",
      type: "Meetup",
      role: "Attendee",
      date: "2026-06-21",
      location: "Philippines / Online",
      summary: "A milestone meetup celebrating three years of the Data Engineering Pilipinas community and sharing practical data engineering knowledge.",
      tags: ["Data Engineering", "Community", "Philippines"],
    },
    {
      title: "Cafe Cursor Manila",
      type: "Meetup",
      role: "Attendee",
      date: "2026-06-16",
      location: "Manila",
      summary: "A casual developer gathering for conversations, co-learning, and exchanging ideas around AI-assisted coding and modern development tools.",
      tags: ["AI", "Developer Tools", "Community"],
    },
    {
      title: "Git It Done: Version Control Basics",
      type: "Workshop",
      role: "Learner",
      date: "2026-06-14",
      location: "Philippines / Online",
      summary: "A beginner-friendly workshop covering the core concepts and everyday workflows of Git and version control.",
      tags: ["Git", "Version Control", "Learning"],
    },
    {
      title: "FIFA × AFC: Agentic Football Cup",
      type: "Competition",
      role: "Participant",
      date: "2026-06-12",
      location: "Philippines / Online",
      summary: "A creative AI competition exploring agentic systems through a football-themed challenge and collaborative building.",
      tags: ["AI Agents", "Competition", "Innovation"],
    },
    {
      title: "GDG Build with AI: The Future of AI and Research",
      type: "Community Event",
      role: "Attendee",
      date: "2026-06-06",
      location: "Philippines / Online",
      summary: "A Google Developer Groups event examining the future of AI, current research directions, and how developers can build with emerging tools.",
      tags: ["AI", "Research", "Google Developer Groups"],
    },
    {
      title: "AWS SBG PUP × PyTorch Philippines: Community Launch and AI Meetup",
      type: "Community Launch",
      role: "Attendee",
      date: "2026-06-05",
      location: "PUP, Manila",
      summary: "A community launch and AI meetup bringing AWS, PyTorch, and local developer communities together for learning and collaboration.",
      tags: ["AI", "AWS", "PyTorch"],
    },
    {
      title: "Microsoft Fabric + Foundry Workshop",
      type: "Workshop",
      role: "Attendee",
      date: "2026-06-03",
      location: "Philippines / Online",
      summary: "A hands-on workshop exploring Microsoft Fabric and Azure AI Foundry for building data and AI solutions on the Microsoft cloud.",
      tags: ["Microsoft Fabric", "Azure AI Foundry", "Data"],
    },
  ],
  blogPosts: [
    {
      title: "Building an OS-style portfolio with Next.js",
      slug: "building-os-portfolio",
      excerpt: "How I built a browser-based desktop OS experience using React, CSS glassmorphism, and the Web Animations API.",
      tags: ["Next.js", "React", "CSS"],
      publishedAt: "2026-07-10",
      featured: true,
    },
  ],
};
